name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests (JSON reporter)
        run: npx playwright test

      - name: Convert Playwright JSON to Xray JSON
        run: node convert-to-xray-json.js

      - name: Upload results to Xray
        env:
          XRAY_CLIENT_ID: ${{ secrets.XRAY_CLIENT_ID }}
          XRAY_CLIENT_SECRET: ${{ secrets.XRAY_CLIENT_SECRET }}
        run: |
          TOKEN=$(curl -s -X POST https://xray.cloud.getxray.app/api/v2/authenticate \
            -H "Content-Type: application/json" \
            -d '{"client_id":"'"$XRAY_CLIENT_ID"'","client_secret":"'"$XRAY_CLIENT_SECRET"'"}')

          TOKEN=$(echo $TOKEN | sed 's/"//g')

          curl -X POST "https://xray.cloud.getxray.app/api/v2/import/execution?testExecKey=ST-103" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $TOKEN" \
            --data @xray-result.json
